/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const IdCardRequest = IDL.Record({
  'memberId' : IDL.Nat,
  'timestamp' : IDL.Int,
  'requestedBy' : IDL.Opt(IDL.Principal),
});
export const LoginActivity = IDL.Record({
  'memberId' : IDL.Nat,
  'timestamp' : IDL.Int,
  'successful' : IDL.Bool,
});
export const SortBy = IDL.Variant({
  'timestampAsc' : IDL.Null,
  'lastNameAsc' : IDL.Null,
  'lastNameDesc' : IDL.Null,
  'timestampDesc' : IDL.Null,
});
export const Filter = IDL.Record({
  'sortBy' : IDL.Opt(SortBy),
  'searchTerm' : IDL.Opt(IDL.Text),
});
export const FileData = IDL.Record({
  'base64Data' : IDL.Text,
  'fileName' : IDL.Text,
  'fileSize' : IDL.Nat,
});
export const Gender = IDL.Variant({
  'other' : IDL.Null,
  'female' : IDL.Null,
  'male' : IDL.Null,
});
export const Member = IDL.Record({
  'id' : IDL.Nat,
  'occupation' : IDL.Text,
  'country' : IDL.Text,
  'gramPanchayat' : IDL.Text,
  'ownerPrincipal' : IDL.Opt(IDL.Principal),
  'aadhaarCardPhoto' : FileData,
  'policeStation' : IDL.Text,
  'email' : IDL.Text,
  'district' : IDL.Text,
  'whatsappNumber' : IDL.Text,
  'state' : IDL.Text,
  'village' : IDL.Text,
  'gender' : Gender,
  'timestamp' : IDL.Int,
  'contactNumber' : IDL.Text,
  'photo' : FileData,
  'fullAddress' : IDL.Text,
  'hashedPassword' : IDL.Text,
  'tehsil' : IDL.Text,
  'lastName' : IDL.Text,
  'firstName' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllIdCardRequests' : IDL.Func([], [IDL.Vec(IdCardRequest)], ['query']),
  'getAllLoginActivities' : IDL.Func([], [IDL.Vec(LoginActivity)], ['query']),
  'getAllMembers' : IDL.Func([IDL.Opt(Filter)], [IDL.Vec(Member)], []),
  'getCallerMember' : IDL.Func([], [IDL.Opt(Member)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getIsCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'loginMember' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(IDL.Nat)], []),
  'registerMember' : IDL.Func([Member], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitIdCardRequest' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const IdCardRequest = IDL.Record({
    'memberId' : IDL.Nat,
    'timestamp' : IDL.Int,
    'requestedBy' : IDL.Opt(IDL.Principal),
  });
  const LoginActivity = IDL.Record({
    'memberId' : IDL.Nat,
    'timestamp' : IDL.Int,
    'successful' : IDL.Bool,
  });
  const SortBy = IDL.Variant({
    'timestampAsc' : IDL.Null,
    'lastNameAsc' : IDL.Null,
    'lastNameDesc' : IDL.Null,
    'timestampDesc' : IDL.Null,
  });
  const Filter = IDL.Record({
    'sortBy' : IDL.Opt(SortBy),
    'searchTerm' : IDL.Opt(IDL.Text),
  });
  const FileData = IDL.Record({
    'base64Data' : IDL.Text,
    'fileName' : IDL.Text,
    'fileSize' : IDL.Nat,
  });
  const Gender = IDL.Variant({
    'other' : IDL.Null,
    'female' : IDL.Null,
    'male' : IDL.Null,
  });
  const Member = IDL.Record({
    'id' : IDL.Nat,
    'occupation' : IDL.Text,
    'country' : IDL.Text,
    'gramPanchayat' : IDL.Text,
    'ownerPrincipal' : IDL.Opt(IDL.Principal),
    'aadhaarCardPhoto' : FileData,
    'policeStation' : IDL.Text,
    'email' : IDL.Text,
    'district' : IDL.Text,
    'whatsappNumber' : IDL.Text,
    'state' : IDL.Text,
    'village' : IDL.Text,
    'gender' : Gender,
    'timestamp' : IDL.Int,
    'contactNumber' : IDL.Text,
    'photo' : FileData,
    'fullAddress' : IDL.Text,
    'hashedPassword' : IDL.Text,
    'tehsil' : IDL.Text,
    'lastName' : IDL.Text,
    'firstName' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllIdCardRequests' : IDL.Func([], [IDL.Vec(IdCardRequest)], ['query']),
    'getAllLoginActivities' : IDL.Func([], [IDL.Vec(LoginActivity)], ['query']),
    'getAllMembers' : IDL.Func([IDL.Opt(Filter)], [IDL.Vec(Member)], []),
    'getCallerMember' : IDL.Func([], [IDL.Opt(Member)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getIsCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'loginMember' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(IDL.Nat)], []),
    'registerMember' : IDL.Func([Member], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitIdCardRequest' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };