/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FileData {
  'base64Data' : string,
  'fileName' : string,
  'fileSize' : bigint,
}
export interface Filter {
  'sortBy' : [] | [SortBy],
  'searchTerm' : [] | [string],
}
export type Gender = { 'other' : null } |
  { 'female' : null } |
  { 'male' : null };
export interface IdCardRequest {
  'memberId' : bigint,
  'timestamp' : bigint,
  'requestedBy' : [] | [Principal],
}
export interface LoginActivity {
  'memberId' : bigint,
  'timestamp' : bigint,
  'successful' : boolean,
}
export interface Member {
  'id' : bigint,
  'occupation' : string,
  'country' : string,
  'gramPanchayat' : string,
  'ownerPrincipal' : [] | [Principal],
  'aadhaarCardPhoto' : FileData,
  'policeStation' : string,
  'email' : string,
  'district' : string,
  'whatsappNumber' : string,
  'state' : string,
  'village' : string,
  'gender' : Gender,
  'timestamp' : bigint,
  'contactNumber' : string,
  'photo' : FileData,
  'fullAddress' : string,
  'hashedPassword' : string,
  'tehsil' : string,
  'lastName' : string,
  'firstName' : string,
}

export interface MemberPublic {
  'id' : bigint,
  'occupation' : string,
  'country' : string,
  'gramPanchayat' : string,
  'policeStation' : string,
  'email' : string,
  'district' : string,
  'whatsappNumber' : string,
  'state' : string,
  'village' : string,
  'gender' : Gender,
  'timestamp' : bigint,
  'contactNumber' : string,
  'fullAddress' : string,
  'tehsil' : string,
  'lastName' : string,
  'firstName' : string,
}
export type SortBy = { 'timestampAsc' : null } |
  { 'lastNameAsc' : null } |
  { 'lastNameDesc' : null } |
  { 'timestampDesc' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'generatePasswordResetOtp' : ActorMethod<[string], [] | [string]>,
  'getAllIdCardRequests' : ActorMethod<[], Array<IdCardRequest>>,
  'getAllLoginActivities' : ActorMethod<[], Array<LoginActivity>>,
  'getAllMembers' : ActorMethod<[[] | [Filter]], Array<Member>>,
  'getCallerMember' : ActorMethod<[], [] | [Member]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getIsCallerAdmin' : ActorMethod<[], boolean>,
  'getMemberById' : ActorMethod<[bigint], [] | [MemberPublic]>,
  'getSiteContent' : ActorMethod<[], Array<[string, string]>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'loginMember' : ActorMethod<[string, string], [] | [bigint]>,
  'registerMember' : ActorMethod<[Member], bigint>,
  'resetMemberPassword' : ActorMethod<[string, string, string], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setSiteContent' : ActorMethod<[string, string], undefined>,
  'setSiteContentBulk' : ActorMethod<[Array<[string, string]>], undefined>,
  'submitIdCardRequest' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];