/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Filter {
    sortBy?: SortBy;
    searchTerm?: string;
}
export interface IdCardRequest {
    memberId: bigint;
    timestamp: bigint;
    requestedBy?: Principal;
}
export interface FileData {
    base64Data: string;
    fileName: string;
    fileSize: bigint;
}
export interface Member {
    id: bigint;
    occupation: string;
    country: string;
    gramPanchayat: string;
    ownerPrincipal?: Principal;
    aadhaarCardPhoto: FileData;
    policeStation: string;
    email: string;
    district: string;
    whatsappNumber: string;
    state: string;
    village: string;
    gender: Gender;
    timestamp: bigint;
    contactNumber: string;
    photo: FileData;
    fullAddress: string;
    hashedPassword: string;
    tehsil: string;
    lastName: string;
    firstName: string;
}
export interface UserProfile {
    name: string;
}
export interface LoginActivity {
    memberId: bigint;
    timestamp: bigint;
    successful: boolean;
}
export enum Gender {
    other = "other",
    female = "female",
    male = "male"
}
export enum SortBy {
    timestampAsc = "timestampAsc",
    lastNameAsc = "lastNameAsc",
    lastNameDesc = "lastNameDesc",
    timestampDesc = "timestampDesc"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAllIdCardRequests(): Promise<Array<IdCardRequest>>;
    getAllLoginActivities(): Promise<Array<LoginActivity>>;
    getAllMembers(filter: Filter | null): Promise<Array<Member>>;
    getCallerMember(): Promise<Member | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getIsCallerAdmin(): Promise<boolean>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    loginMember(emailOrPhone: string, password: string): Promise<bigint | null>;
    registerMember(member: Member): Promise<bigint>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitIdCardRequest(memberId: bigint): Promise<void>;
}
import type { FileData as _FileData, Filter as _Filter, Gender as _Gender, IdCardRequest as _IdCardRequest, Member as _Member, SortBy as _SortBy, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllIdCardRequests(): Promise<Array<IdCardRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllIdCardRequests();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllIdCardRequests();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllLoginActivities(): Promise<Array<LoginActivity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLoginActivities();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLoginActivities();
            return result;
        }
    }
    async getAllMembers(arg0: Filter | null): Promise<Array<Member>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMembers(to_candid_opt_n7(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMembers(to_candid_opt_n7(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerMember(): Promise<Member | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerMember();
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerMember();
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIsCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getIsCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIsCallerAdmin();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async loginMember(arg0: string, arg1: string): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.loginMember(arg0, arg1);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginMember(arg0, arg1);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerMember(arg0: Member): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.registerMember(to_candid_Member_n22(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerMember(to_candid_Member_n22(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitIdCardRequest(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitIdCardRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitIdCardRequest(arg0);
            return result;
        }
    }
}
function from_candid_Gender_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Gender): Gender {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_IdCardRequest_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IdCardRequest): IdCardRequest {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Member_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Member): Member {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Member]): Member | null {
    return value.length === 0 ? null : from_candid_Member_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    occupation: string;
    country: string;
    gramPanchayat: string;
    ownerPrincipal: [] | [Principal];
    aadhaarCardPhoto: _FileData;
    policeStation: string;
    email: string;
    district: string;
    whatsappNumber: string;
    state: string;
    village: string;
    gender: _Gender;
    timestamp: bigint;
    contactNumber: string;
    photo: _FileData;
    fullAddress: string;
    hashedPassword: string;
    tehsil: string;
    lastName: string;
    firstName: string;
}): {
    id: bigint;
    occupation: string;
    country: string;
    gramPanchayat: string;
    ownerPrincipal?: Principal;
    aadhaarCardPhoto: FileData;
    policeStation: string;
    email: string;
    district: string;
    whatsappNumber: string;
    state: string;
    village: string;
    gender: Gender;
    timestamp: bigint;
    contactNumber: string;
    photo: FileData;
    fullAddress: string;
    hashedPassword: string;
    tehsil: string;
    lastName: string;
    firstName: string;
} {
    return {
        id: value.id,
        occupation: value.occupation,
        country: value.country,
        gramPanchayat: value.gramPanchayat,
        ownerPrincipal: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.ownerPrincipal)),
        aadhaarCardPhoto: value.aadhaarCardPhoto,
        policeStation: value.policeStation,
        email: value.email,
        district: value.district,
        whatsappNumber: value.whatsappNumber,
        state: value.state,
        village: value.village,
        gender: from_candid_Gender_n15(_uploadFile, _downloadFile, value.gender),
        timestamp: value.timestamp,
        contactNumber: value.contactNumber,
        photo: value.photo,
        fullAddress: value.fullAddress,
        hashedPassword: value.hashedPassword,
        tehsil: value.tehsil,
        lastName: value.lastName,
        firstName: value.firstName
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    memberId: bigint;
    timestamp: bigint;
    requestedBy: [] | [Principal];
}): {
    memberId: bigint;
    timestamp: bigint;
    requestedBy?: Principal;
} {
    return {
        memberId: value.memberId,
        timestamp: value.timestamp,
        requestedBy: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.requestedBy))
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    female: null;
} | {
    male: null;
}): Gender {
    return "other" in value ? Gender.other : "female" in value ? Gender.female : "male" in value ? Gender.male : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Member>): Array<Member> {
    return value.map((x)=>from_candid_Member_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_IdCardRequest>): Array<IdCardRequest> {
    return value.map((x)=>from_candid_IdCardRequest_n4(_uploadFile, _downloadFile, x));
}
function to_candid_Filter_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Filter): _Filter {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_Gender_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): _Gender {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function to_candid_Member_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Member): _Member {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_SortBy_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortBy): _SortBy {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Filter | null): [] | [_Filter] {
    return value === null ? candid_none() : candid_some(to_candid_Filter_n8(_uploadFile, _downloadFile, value));
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    occupation: string;
    country: string;
    gramPanchayat: string;
    ownerPrincipal?: Principal;
    aadhaarCardPhoto: FileData;
    policeStation: string;
    email: string;
    district: string;
    whatsappNumber: string;
    state: string;
    village: string;
    gender: Gender;
    timestamp: bigint;
    contactNumber: string;
    photo: FileData;
    fullAddress: string;
    hashedPassword: string;
    tehsil: string;
    lastName: string;
    firstName: string;
}): {
    id: bigint;
    occupation: string;
    country: string;
    gramPanchayat: string;
    ownerPrincipal: [] | [Principal];
    aadhaarCardPhoto: _FileData;
    policeStation: string;
    email: string;
    district: string;
    whatsappNumber: string;
    state: string;
    village: string;
    gender: _Gender;
    timestamp: bigint;
    contactNumber: string;
    photo: _FileData;
    fullAddress: string;
    hashedPassword: string;
    tehsil: string;
    lastName: string;
    firstName: string;
} {
    return {
        id: value.id,
        occupation: value.occupation,
        country: value.country,
        gramPanchayat: value.gramPanchayat,
        ownerPrincipal: value.ownerPrincipal ? candid_some(value.ownerPrincipal) : candid_none(),
        aadhaarCardPhoto: value.aadhaarCardPhoto,
        policeStation: value.policeStation,
        email: value.email,
        district: value.district,
        whatsappNumber: value.whatsappNumber,
        state: value.state,
        village: value.village,
        gender: to_candid_Gender_n24(_uploadFile, _downloadFile, value.gender),
        timestamp: value.timestamp,
        contactNumber: value.contactNumber,
        photo: value.photo,
        fullAddress: value.fullAddress,
        hashedPassword: value.hashedPassword,
        tehsil: value.tehsil,
        lastName: value.lastName,
        firstName: value.firstName
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sortBy?: SortBy;
    searchTerm?: string;
}): {
    sortBy: [] | [_SortBy];
    searchTerm: [] | [string];
} {
    return {
        sortBy: value.sortBy ? candid_some(to_candid_SortBy_n10(_uploadFile, _downloadFile, value.sortBy)) : candid_none(),
        searchTerm: value.searchTerm ? candid_some(value.searchTerm) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortBy): {
    timestampAsc: null;
} | {
    lastNameAsc: null;
} | {
    lastNameDesc: null;
} | {
    timestampDesc: null;
} {
    return value == SortBy.timestampAsc ? {
        timestampAsc: null
    } : value == SortBy.lastNameAsc ? {
        lastNameAsc: null
    } : value == SortBy.lastNameDesc ? {
        lastNameDesc: null
    } : value == SortBy.timestampDesc ? {
        timestampDesc: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): {
    other: null;
} | {
    female: null;
} | {
    male: null;
} {
    return value == Gender.other ? {
        other: null
    } : value == Gender.female ? {
        female: null
    } : value == Gender.male ? {
        male: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
